### ISSUE TITLE
Please consider adding a rust version

### ISSUE THREAD

**Issue by szbergeron** [GriffinLeclerc/Lunar-Coins-Adder#1]
I'm concerned about system security using this application and would like to see the core logic migrated to Rust or a similar language

**Comment by GriffinLeclerc** [comment]
All desired functionality has already been written in Python 3. Unfortunately, rewriting the entire application in Rust or a similar language would take far too much time for little benefit.
In addition, all team members have separate healthcare providers. Exposure to Rust may cause Tetanus or similar medical conditions.

**Comment by szbergeron** [comment]
no
